before_install: cd src

language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - npm i
  - npm run build
  
script:
  - npm run generate
